name: cloud_provision_shared
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.0
  googleapis_auth: ^1.4.1

dev_dependencies:
  googleapis: ^11.3.0
  flutter_dotenv: ^5.0.2